# Generated by Django 5.2.11 on 2026-03-18 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DdosDataset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ddos_data', models.TextField()),
                ('attack_result', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'DDOS_DATASET',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('experience', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'FEEDBACK',
            },
        ),
        migrations.CreateModel(
            name='PoliceRegister',
            fields=[
                ('police_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('badge_number', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'POLICE_REGISTER',
            },
        ),
        migrations.CreateModel(
            name='RequestToAdmin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ddos_data', models.TextField()),
                ('attack_result', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'REQUEST_TO_ADMIN',
            },
        ),
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='shared_files/%Y/%m/%d/')),
                ('message', models.TextField(blank=True)),
                ('scan_result', models.CharField(choices=[('CLEAN', 'Clean'), ('MALICIOUS', 'Malicious'), ('PENDING', 'Pending'), ('ERROR', 'Scan Error')], default='PENDING', max_length=10)),
                ('scan_details', models.TextField(blank=True)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_files', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'FILEDATA',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('attack_id', models.AutoField(primary_key=True, serialize=False)),
                ('attack_type', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rank', models.IntegerField(default=0)),
                ('file_id', models.ForeignKey(blank=True, db_column='file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attacks', to='accounts.filedata')),
            ],
            options={
                'db_table': 'ATTACK',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CyberCrimeReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('crime_type', models.CharField(choices=[('PHISHING', 'Phishing'), ('MALWARE', 'Malware'), ('IDENTITY_THEFT', 'Identity Theft'), ('FRAUD', 'Online Fraud'), ('HARASSMENT', 'Cyber Harassment'), ('DATA_BREACH', 'Data Breach'), ('DDOS', 'DDoS Attack'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWING', 'Under Review'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=15)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('assigned_police', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to='accounts.policeregister')),
            ],
            options={
                'db_table': 'CYBER_CRIME_REPORT',
                'ordering': ['-date_reported'],
            },
        ),
        migrations.CreateModel(
            name='ThreatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('threat_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='HIGH', max_length=10)),
                ('details', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('file_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threats', to='accounts.filedata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threat_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'THREAT_LOG',
                'ordering': ['-detected_at'],
            },
        ),
    ]
