# Generated by Django 5.2.11 on 2026-03-19 04:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cybercrimereport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='cybercrimereport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cybercrimereport',
            name='evidence_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cybercrimereport',
            name='title',
            field=models.CharField(default='Untitled Report', max_length=255),
        ),
        migrations.AddField(
            model_name='cybercrimereport',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='policeregister',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='policeregister',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
