# Generated by Django 5.2.11 on 2026-03-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_cybercrimereport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policeregister',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='policeregister',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=10),
        ),
    ]
